### ISSUE TITLE
Support S/N JCorB 8th gen

### ISSUE THREAD

**Issue by terminet85** [rboldini/CoreBook_X_OC#11]
Hello!
There is a fork for 8th gen https://github.com/weachy/CoreBookX-14-Hackintosh 
But I got a new CoreBooX gen8 revision (aka green motherboard version). I'll tried to use that OpenCore EFI, but I hang with this error:

```
No argument are initialized for method [FCPU]

ACPI Error: Method parse/execution failed [\LIDP.FCPU] (Node ffffff937a22a5a8 RE_NOT_FOUND (28160938/psparse-632)
ACPI Error: [\_SB_.PC18.LPC.H_EC.ADP1._PSR] Namespace lookup failure, RE_NOT_FOUND (28160938/psargs-463)
[FCPU] @00093 #882D:

Initialized Local Variables for method [FCPU]:
     Local0: ffffff9379f86500 <Obj>         Integer: 0000000000000001
```

Any advice for what should do I look in order to fix first this error?
I'll share any fix that I could make, making a new branch of this git :)

Thank you so much

**Comment by terminet85** [comment]
Disabling SSDT-LID-AC-Fix.aml I've installed MacOS. 
Wireless is working.
Suspend mode too.
Bad touchpad
No audio
No battery

I'm keep to investigate furthermore. SSDT-LID-AC-Fix.aml what is?

**Comment by rboldini** [comment]
Here a working repo 
[https://github.com/sqlsec/CHUWI-COREBOOK-X-I5-8259U](https://github.com/sqlsec/CHUWI-COREBOOK-X-I5-8259U)

Ssdt-lid-ac is not necessary for your model, is a fix for sleep by lid close and power adapter detection also ssdt bat is unnecessary and ssdt gpio with i2c trackpad implementation is different from mine in sqlsec's repo.

[Your model also seems to be shipped in two variant:
- Intel's Wi-Fi chipset
- Realtek Wi-Fi chipset
The second one is not compatible with macOS neither exist a kext in developing.]

**Comment by terminet85** [comment]
Thank you for your reply and help!

I've used that repo (your fork) https://github.com/weachy/CoreBookX-14-Hackintosh and I've disabled SSDT-LID-AC-Fix.aml and I was able to boot installer and got a working MacOS.

Looking weachy fork there is a lot of changing beyond config.plist, however I got some no working features:

-Trackpad left click or soft click doesn't work
-No battery
-No Audio
-No multifunction (e.g. brightness)

Wireless is working :) Any advice for how fix these issues?

**Comment by terminet85** [comment]
@rboldini If you help me to fix battery, touchpad and audio (that is missing)... I'm ready to make a donation in order to thank you for spending ur time in this, let me know if you have time to :)

**Comment by rboldini** [comment]
It is not for donations that I carry out this project.
If you think my work is interesting or useful, you are welcome to contribute with a donation.

Said that, my advice is to prepare everything from scratch:

1. Download from [Acidanthera's  OpenCore repo](https://github.com/acidanthera/OpenCorePkg) latest Release. (0.7.7 right now)
2. Download essentials Kext such as, Lilu, Whatevergreen, VirtualSMC, NVMeFixup, AirportItlwm (alpha recommended), ECEnabler, etc..

In general you can follow [Dortania's Guide](https://dortania.github.io/OpenCore-Install-Guide/prerequisites.html)

Your model also doesn't need an SSDT-BATT for my experience.

Be sure to follow Dortania's Guide under Coffee Lake and Whiskey Lake when needed.

Just for the touchpad be sure to follow this order in config.plist:

0. PS2 Input 
1. PS2 Controller
2. PS2 Keyboard
3. VoodooI2C GPIO
4. VoodooI2C Services
5. VoodooI2C
6. VoodooI2C HID

Others related kext (PS2 or VoodooI2C) need to bee disabled.

**Comment by Anycubic** [comment]
@terminet85 I have same Corebook version and tying to make it work with Big Sur, we can collaborate if you want, just let me know how to get in touch, there are no private messages in github, thanks

**Comment by Anycubic** [comment]
@rboldini could you please keep at least this issue opened? I'm willing to collaborate but if you close all of the related issues it's going to be hard! Thank you

**Comment by Anycubic** [comment]
> Just for those kexts.
> 
> 0. PS2 Input
> 1. PS2 Controller
> 2. PS2 Keyboard
> 3. VoodooI2C GPIO
> 4. VoodooI2C Services
> 5. VoodooI2C
> 6. VoodooI2C HID
> 
> Others related kext (PS2 or VoodooI2C) need to bee disabled.

@rboldini like this?
![2022-01-27_10-57-19](https://user-images.githubusercontent.com/31375394/151335984-9642533f-ecea-4435-b6aa-5bd0a5df2017.jpg)

**Comment by Anycubic** [comment]
> Your model also seems to be shipped in two variant:
> 
> Intel's Wi-Fi chipset
> Realtek Wi-Fi chipset
> The second one is not compatible with macOS neither exist a kext in developing.

Luckily I have Intel! Should be possibile to fix audio (seems ALC269 and not ALC867) and trackpad. I also will implement your battery advices and report back. Do you you think it will be usefull extracting again all of the DSDT table e creating proper .aml? Sorry if I say nonsense, I started playing with Hackintosh when OpenCore didn't exist at all, now I need to learn again, thanks.

**Comment by terminet85** [comment]
Hey @Anycubic :)
As told by @rboldini I've restarted from scratch (less or more). I spent last two day to fix battery (yeah works now), you're lucky.

Audio was only to find the right layout-id, and touchpad fixed itself, configuration appeared when fixed battery.

I need to write the patch, because for debugging I'll modded directly to DSDT. When ready I'll make a GitHub

**Comment by rboldini** [comment]
The 8th Gen model I have, doesn't need battery patch in DSDT, I just need SMCBatteryManager and ECEnabler kexts.
I haven't tried more on it cause of Realtek WiFi chipset.

**Comment by Anycubic** [comment]
@terminet85 that's pretty a good news! If you want you can make a fork and push there your mods so I can test them as well on my unit. Which is the audio right layouu-id? Thanks

**Comment by terminet85** [comment]
@rboldini but not this case. I needed to fix either ADP1 Device, _BIF and _BST.
@Anycubic give me time to make patch...

**Comment by Anycubic** [comment]
@terminet85 ok I'll wait. Just let me know should you need any help 😉

**Comment by Anycubic** [comment]
I'm trying to install by myself (mostly to understand how OpenCore works, this is my first install). I got stuck here:

`[EB|LOG:EXITBS:START]
`
before you ask I'm sure I turned off `CFG Lock` in BIOS, what could it be possible be?

Thanks

**Comment by rboldini** [comment]
Some quirk in OC maybe try to match with my config quirks like ProvideCustomSlide etc..

To be sure inside the OC Release there is Documentation/Doc folder, where you can find a pdf with every quirk explained.

**Comment by Anycubic** [comment]
YES it did it! I got past and now I'm in the install screen but... everything is chinese! In which menu  can I change the language? Thanks!

**Comment by Anycubic** [comment]
Ma sei italiano de Roma! 🤣  Ok, I guess I figured it out, don't want to spoil this issue thread anymore. Grazie 1000!

**Comment by rboldini** [comment]
Esattamente, però non romano di nascita.

Se volete si può fare un canale discord per organizzarvi.

In some time there will be an open project manager for this repo with every issue I found, in order to get some help.

Inviato da iPhone

**Comment by terminet85** [comment]
Allora è qui la festa 😂
Un po’ più al nord San Marino 
Ok per discord ✌️

**Comment by Anycubic** [comment]
I soliti italiani caciaroni! 🤣  anche a me va bene discord. Ultima informazione di servizio e poi taccio: @terminet85 I've installed it starting from scratch and it is working fine (well, I least booted). I need to fix battery and other details, so please let me know when you will publish your work 😉

**Comment by rboldini** [comment]
Please upload here your decompiled DSDT (.dal) to let me check what’s wrong with your battery.

Also seems weachy’s repo is updated with my latest changes, no credit are given, but they are using my ASL patches.

Don’t use this repo, it’s unsafe.

Inviato da iPhone

**Comment by Anycubic** [comment]
Right now I'm using this AML, from weachy's repo, I don't know if I can disable anything which maybe i affecting battery. Also mac model is wrong and not recognised:
![2022-01-28_13-51-55](https://user-images.githubusercontent.com/31375394/151550672-ea3f536c-1750-452e-bac8-0223eb9db930.jpg)

I extracted the DSDT.bin before erasing Windows partition. But do you need me to extract if from my Hackintosh, right? If this is what you need how can I do that? Thanks

**Comment by rboldini** [comment]
Not exactly, you can dump it from windows with ssdttime, Clover, OC Debug version or with patchmatic.

[Guide](https://www.tonymacx86.com/threads/guide-patching-laptop-dsdt-ssdts.152573/)

Here you can find most detailed guide i know for dsdt patching.

Just follow to the disassembling method and get your disassembled dsdt (.dsl format)

Then we'll use it to code some hot-patch.

**Comment by Anycubic** [comment]
Ok, I'll see what I can do. Right know I have my DSDT.bin extracted with RWEverything in Windows. Could it be useful for you? Otherwise I will follow the guide to extract it from hackintosh side

**Comment by rboldini** [comment]
I’ve not experience with binary ASL, really don’t know how to edit or disassembly it.

Just do an usb stick formatted GPT, mount EFI put latest version of clover, boot it, press F4 or FN+F4, reboot on OC and the job is done.

Now in EFI/Clover/ACPI/origin you have your assembled DSDT/SSDT.

Follow the guide below to disassembly it.

Inviato da iPhone

**Comment by Anycubic** [comment]
Ok, I'll do it this evening, now I'm at work 😉

**Comment by terminet85** [comment]
[SSDT-CHUWI-JCorB-BATT.zip](https://github.com/rboldini/CoreBook_X_OC/files/7960210/SSDT-CHUWI-JCorB-BATT.zip)
```
                <dict>
                    <key>Base</key>
                    <string></string>
                    <key>BaseSkip</key>
                    <integer>0</integer>
                    <key>Comment</key>
                    <string>_BIF to XBIF</string>
                    <key>Count</key>
                    <integer>0</integer>
                    <key>Enabled</key>
                    <true/>
                    <key>Find</key>
                    <data>X0JJRgA=</data>
                    <key>Limit</key>
                    <integer>0</integer>
                    <key>Mask</key>
                    <data></data>
                    <key>OemTableId</key>
                    <data></data>
                    <key>Replace</key>
                    <data>WEJJRgA=</data>
                    <key>ReplaceMask</key>
                    <data></data>
                    <key>Skip</key>
                    <integer>0</integer>
                    <key>TableLength</key>
                    <integer>0</integer>
                    <key>TableSignature</key>
                    <data></data>
                </dict>
                <dict>
                    <key>Base</key>
                    <string></string>
                    <key>BaseSkip</key>
                    <integer>0</integer>
                    <key>Comment</key>
                    <string>_BST to XBST</string>
                    <key>Count</key>
                    <integer>0</integer>
                    <key>Enabled</key>
                    <true/>
                    <key>Find</key>
                    <data>X0JTVA==</data>
                    <key>Limit</key>
                    <integer>0</integer>
                    <key>Mask</key>
                    <data></data>
                    <key>OemTableId</key>
                    <data></data>
                    <key>Replace</key>
                    <data>WEJTVA==</data>
                    <key>ReplaceMask</key>
                    <data></data>
                    <key>Skip</key>
                    <integer>0</integer>
                    <key>TableLength</key>
                    <integer>0</integer>
                    <key>TableSignature</key>
                    <data></data>
                </dict>
                   <dict>
                    <key>Base</key>
                    <string></string>
                    <key>BaseSkip</key>
                    <integer>0</integer>
                    <key>Comment</key>
                    <string>BAT0 to XBAT</string>
                    <key>Count</key>
                    <integer>0</integer>
                    <key>Enabled</key>
                    <true/>
                    <key>Find</key>
                    <data>QkFUMA==</data>
                    <key>Limit</key>
                    <integer>0</integer>
                    <key>Mask</key>
                    <data></data>
                    <key>OemTableId</key>
                    <data></data>
                    <key>Replace</key>
                    <data>WEJBVA==</data>
                    <key>ReplaceMask</key>
                    <data></data>
                    <key>Skip</key>
                    <integer>0</integer>
                    <key>TableLength</key>
                    <integer>0</integer>
                    <key>TableSignature</key>
                    <data></data>
                </dict>

```
Here we go. Let's try it. This fix costed me days and days of research and ASL writing...

**Comment by Anycubic** [comment]
> Here we go. Let's try it. This fix costed me days and days of research and ASL writing...

You are fast! I hope Xiānshēng Wheaky will at least thank you this time! 😉 

Thanks, I'm going to test it

**Comment by terminet85** [comment]
I've forgot to add _BIF to XBIF and _BST to BST, I've fix'd

**Comment by Anycubic** [comment]
> I've forgot to add _BIF to XBIF and _BST to BST, I've fix'd

I'm sorry, where do I need to add the patches? Here? And how? I wan't able to find good information on how to do it

![2022-01-28_19-48-33](https://user-images.githubusercontent.com/31375394/151604343-53cb9ff0-ac11-4651-b6db-8ae4ee3de930.jpg)

I guess I also need to delete that line _BIF to XBIF? In general maybe it could be useful should you create a fork with your OpenCore files so that we can work on the same configuration/kext/etc

**Comment by Anycubic** [comment]
> Not exactly, you can dump it from windows with ssdttime, Clover, OC Debug version or with patchmatic.
> 
> [Guide](https://www.tonymacx86.com/threads/guide-patching-laptop-dsdt-ssdts.152573/)
> 
> Here you can find most detailed guide i know for dsdt patching.
> 
> Just follow to the disassembling method and get your disassembled dsdt (.dsl format)
> 
> Then we'll use it to code some hot-patch.

@rboldini  here 😉 

[DSDT.dsl.zip](https://github.com/rboldini/CoreBook_X_OC/files/7961650/DSDT.dsl.zip)

**Comment by rboldini** [comment]
Mi confermate che il DSDT di @Anycubic è uguale a quello di @terminet85 ?

Se si la patch che hai scritto potrebbe essere sbagliata

**Comment by Anycubic** [comment]
Non so su quello di @terminet85, il mio Corebook è un JCorB con WIFI Intel e chip audio id=2. Ho seguito pedissequamente le istruzioni che mi hai dato

**Comment by terminet85** [comment]
[SSDT-CHUWI-JCorB-BATT.aml.zip](https://github.com/rboldini/CoreBook_X_OC/files/7963254/SSDT-CHUWI-JCorB-BATT.aml.zip)

@Anycubic Maybe first read this https://dortania.github.io/OpenCore-Install-Guide/prerequisites.html you need some knowledge to sort out...
You need SMCBatteryManager.kext and its dependency.

@rboldini That's same, sure there is something wrong I'm a newbie, what's your hints?

---

There is a new version, I've implemented 16byte to 8byte conversion, so its doesn't need anymore to load ECEnabler.kext, and I've re-write _OSI check strategy

**Comment by rboldini** [comment]
First of all you doesn't need to avoid ECEnabler injection, it actually helps a lot.

I noticed you removed some operation from bif and bst method.
Why? Where do you find out what's stored inside your EC's fields ?

Your new BAT method need to be BAT0 and not XBAT, to do not broke the xbat patch you apply by OC.
That patch is useless u don't need to change the whole BAT device, just overload methods that need some modification.

**Comment by terminet85** [comment]
ECEnabler is only a 16bytes to 8bytes convertor, IMHO is much better done this conversion directly on the patch.

I've followed the ACPI 6.4 specs: https://uefi.org/specs/ACPI/6.4/10_Power_Source_and_Power_Meter_Devices/Power_Source_and_Power_Meter_Devices.html

I cannot overload a method that is already defined. _STA BAT0's method  isn't return 0x1F (battery present), and I cannot patch only this method with OC.

**Comment by terminet85** [comment]
[SSDT-CHUWI-JCorB-BATT.aml.zip](https://github.com/rboldini/CoreBook_X_OC/files/7965740/SSDT-CHUWI-JCorB-BATT.aml.zip)

Added fake S/N in order to fix Service Recommended warning.
Hardcoded _BIF 0x01 and 0x04 to be more ACPI 6.4 compliant.

**Comment by rboldini** [comment]
You should, look at mine just bst and bif are touched

Inviato da iPhone

**Comment by Anycubic** [comment]
> [SSDT-CHUWI-JCorB-BATT.aml.zip](https://github.com/rboldini/CoreBook_X_OC/files/7965740/SSDT-CHUWI-JCorB-BATT.aml.zip)
> 
> Added fake S/N in order to fix Service Recommended warning. Hardcoded _BIF 0x01 and 0x04 to be more ACPI 6.4 compliant.

Thanks, I'll test it

**Comment by rboldini** [comment]
Be aware that I’ve te reports the S/N issue to Acidanthera’s Group, you can find it in acidanthera/bugtracker.
It will be fixed in future versions of VirtualSMC/SMCBatteryManager and the S/N injection will be useless.
Inviato da iPhone

**Comment by Anycubic** [comment]
> Be aware that I’ve te reports the S/N issue to Acidanthera’s Group, you can find it in acidanthera/bugtracker. It will be fixed in future versions of VirtualSMC/SMCBatteryManager and the S/N injection will be useless. Inviato da iPhone

Ok. I still didn't understand if and where I need to patch _BIF to XBIF, _BST to BST and BAT to BAT0 with that code that @terminet85 has provided. I'm good in reading and following directions but I need a specific place where I can find specific information.

Thanks 😉

**Comment by Anycubic** [comment]
While looking for how to apply those battery patch on the Net, I installed 10.15.7 as well and it is working pretty fine! Webcam is working (though little bit too dark, don't know if it is just crappy camera fault) also internal micro-sd reader is working fine. The only thing still missing is guess what? The battery! 🤣

**Comment by terminet85** [comment]
Does your Ambient Light Sensor work? On my version it doesn’t work either on Windows and MacOS.
Anyway I can find ALSD Device on my DSDT…

**Comment by Anycubic** [comment]
These are the other issues I have:
- closing the lid doesn't make the MacBook go to sleep (but sleep works fine)
- trackpad soft clicks don't work

As you said, light sensor is selectable but it seems not working. I didn't check it under Windows, I'll try to understand if it's not working by definition and will never work actually. Can you take a screenshot of your DSDT devices? Thanks

**Comment by rboldini** [comment]
Ambient la sensor is not just light sensor, it detect the brightness of the screen and where colors are lighter, and change color profile.

On windows it work, on macos I had some problems with the srgb color profile.

Light sensors instead detects how many light is the room to change brightness 

Inviato da iPhone

**Comment by rboldini** [comment]
For lid fix, I helped someone there:


https://www.reddit.com/r/hackintosh/comments/ptzftq/looking_for_help_debugging_some_acpi_issues_with/?utm_source=share&utm_medium=ios_app&utm_name=iossmf


The issue was on ADP1 but this works also for LID0 in my case.
Try following those instruction.


For battery fix try to take a look on what smcbattery/ACPIBattery say in debug mode.


Inviato da iPhone

**Comment by terminet85** [comment]
> * closing the lid doesn't make the MacBook go to sleep (but sleep works fine)

[SSDT-LID-AC-Fix.zip](https://github.com/rboldini/CoreBook_X_OC/files/7969202/SSDT-LID-AC-Fix.zip)
```
                <dict>
                    <key>Arch</key>
                    <string>Any</string>
                    <key>BundlePath</key>
                    <string>ACPIPoller.kext</string>
                    <key>Comment</key>
                    <string>V0.8.1</string>
                    <key>Enabled</key>
                    <true/>
                    <key>ExecutablePath</key>
                    <string>Contents/MacOS/ACPIPoller</string>
                    <key>MaxKernel</key>
                    <string></string>
                    <key>MinKernel</key>
                    <string></string>
                    <key>PlistPath</key>
                    <string>Contents/Info.plist</string>
                </dict>
```

> * trackpad soft clicks don't work

You need to load my  battery Patch and VirtualSMC's Kext how I've already told to you to do and trackpad settings will appears.

**Comment by terminet85** [comment]
> Ambient la sensor is not just light sensor

How is it named? Because I'm pretty 99% that this laptop version doesn't have it.

**Comment by rboldini** [comment]
ALSD, it work on Windows on my model.

It’s an annoying thing that change brightness without reason I’m keeping it disabled in both windows/macos.

I notice it a lot when playing  DRM HDR content.

Inviato da iPhone

**Comment by terminet85** [comment]
Ok, Just waiting @Anycubic to confirm that ALSD doesn't work under Windows to give up.

**Comment by Anycubic** [comment]
I'll check everything later this afternoon, very busy atm

**Comment by Anycubic** [comment]
> > Ambient la sensor is not just light sensor
> 
> How is it named? Because I'm pretty 99% that this laptop version doesn't have it.

On Mac is named "brightness" and it does not work even if I can check and uncheck it (I mean automatic brightness, need to check about color profile chang). I now totally erased any trace of Windows on my SSD, just waste of space AFAIC

**Comment by Anycubic** [comment]
> You need to load my battery Patch and VirtualSMC's Kext how I've already told to you to do and trackpad settings will appears.

I got it at the end... battery and trackpad are now working nicely 😉  next step will be checking an external monitor (tomorrow I'll get the needed adapter)

**Comment by terminet85** [comment]
Not a good idea wipe windows…
Check on macos Is pretty useless.

**Comment by Anycubic** [comment]
I have a Mac Mini since 2012 (I used to be a Windows user before) and never regretted the shift. Parallels with Windows is more than enough for me 😉

**Comment by Anycubic** [comment]
Reporting also that:
- keyboard light is working fine from keyboard (two levels of lights are available)
- audio fn+vol- and fn+vol+ are also working fine
- fn + brightness keys are not working
- I need to check the microphone yet

**Comment by terminet85** [comment]
I've some good and bad news.
- I patched method _Q0A, in order to get update from plug/unplug AC adapter;
- Fixed the brightness key, but I'm facing same problem as @rboldini (lag on ACPI Key);
- Removed the BATX patch. I found out _INI Method is "Initialize" so I've set ECWR to 0x02, to get battery on.
- I'll give up to ALSD, is not working on my Windows, so either could be broken in my setup or not installed in this version.

**Comment by Anycubic** [comment]
Very fine @terminet85 ! Did you attach the new version? I can't find it.

I also have some news. I'm testing the external screen. It works fine until you want to work in clamshell mode: the external screen don't switch off but it's like if it lose sync and goes black. Maybe I need to check if in some ways for some reason while in clamshell mode the external monitor gets a higher frequency / resolution that can handle. I'll work on it

**Comment by Anycubic** [comment]
> I also have some news. I'm testing the external screen. It works fine until you want to work in clamshell mode: the external screen don't switch off but it's like if it lose sync and goes black. Maybe I need to check if in some ways for some reason while in clamshell mode the external monitor gets a higher frequency / resolution that can handle. I'll work on it

I solved my issue, indeed it was my USB-C -> HDMI crappy converter doing max 60Hz while my monitor was saying 72Hz...I had to log in with AnyDesk and changed the frequency. Now external monitor is working fine even with the lid closed.

**Comment by terminet85** [comment]
Sorry I haven't any external monitor to debug.
I've released my work here: https://github.com/terminet85/CoreBook_X_Gen8_JCorB_OC

**Comment by Anycubic** [comment]
Very good! I'll help you as much as I can. External monitor is working fine 😉

**Comment by Anycubic** [comment]
Sorry if I ask this strange question, I need to wake my Corebook up while sleeping in clamshell mode. Usb keyboard is able to wakeup a real Mac but it seems it's not working, everytime I need to open the lid in order to wake my Corebook up.... @terminet85 and @rboldini did you also have this behaviour? Thanks

**Comment by jgfeliz** [comment]
> Sorry I haven't any external monitor to debug. I've released my work here: https://github.com/terminet85/CoreBook_X_Gen8_JCorB_OC

hi, i try this solutions, but my chuwi show me this message: 

support.apple.com/mac/startup

my SN is: JCorBXD...

**Comment by terminet85** [comment]
Please open an issue on https://github.com/terminet85/CoreBook_X_Gen8_JCorB_OC

@rboldini thanks for your help. Check your PayPal ❤️
