### ISSUE TITLE
MSR Lock

### ISSUE THREAD

**Issue by Weddin** [rboldini/CoreBook_X_OC#5]
Hello. Did you investigate MSR locking? Anybody have a dump UEFI?
It'll help to improvement performance (DVMT unlocking is also requiring dump) and power management

**Comment by rboldini** [comment]
Actually nothing done for MSR.
About DVMT it is unlocked BIOS side, and can be easily changed from 32M to 64M

**Comment by Weddin** [comment]
Does itlwm not working with airdrop? I have Xiaomi pro gtx, but I don't use airdrop. MSR unlock gives me more performance.

**Comment by rboldini** [comment]
Intel AC7XXX and 8XXX can't use at same time Bluetooth and WiFi, at least not with 4.0 pairing, that's why I want a Broadcom chipset instead.
Airdrop and handoff are WIP in itlwm.

**Comment by Weddin** [comment]
@rboldini I just tested  Intel Wireless-AC 8265 on Xiaomi pro gtx now. Bluetooth and wifi work together very well.

**Comment by rboldini** [comment]
@Weddin 
For latest do you mean Airport 1.3.0 and Bluetooth 1.1.3 or Alpha 2.0 versions?
I'm on latest stable version and can't get work together BT and WIFI, looking at issue section on the repo, I've found many request for this problem.

**Comment by Weddin** [comment]
@rboldini Sorry, I'm using alpha version of itlwm

**Comment by rboldini** [comment]
@Weddin Thanks, I preferred the stable because of work, but I will try the alpha tonight!

**Comment by Weddin** [comment]
MSR can be unlocked in BIOS. This setting is not hided
