### ISSUE TITLE
Bluetooth with wifi

### ISSUE THREAD

**Issue by Weddin** [rboldini/CoreBook_X_OC#6]
@Weddin Thanks, I preferred the stable because of work, but I will try the alpha tonight!

UPDATE: 
Still not working, any settings is different? usb settings?
Bluetooth Port is set on internal or USB3?
Fixed region in boot_arg (itlwm_cc=XX)?
OC version 0.7.0 or 0.7.1?
Thanks in advance

_Originally posted by @rboldini in https://github.com/rboldini/CoreBook_X_OC/issues/5#issuecomment-887761255_

**Comment by Weddin** [comment]
I'm using clover KBL on my Xiaomi Notebook pro gtx. https://github.com/daliansky/XiaoMi-Pro-Hackintosh/tags version 1.5.8
Bluetooth working on USB 3.0 Bus in System Information
`Bluetooth HCI:

  Product ID:	0x0a2b
  Vendor ID:	0x8087  (Intel Corporation)
  Version:	0.10
  Speed:	Up to 12 Mb/s
  Location ID:	0x14400000 / 2
  Current Available (mA):	500
  Current Required (mA):	100
  Extra Operating Current (mA):	0
  Built-In:	Yes`

**Comment by rboldini** [comment]
my product id is 0x0a2a
Bug in AirportItlwm > https://github.com/OpenIntelWireless/itlwm/issues/482
